jmeter.save.saveservice.print_field_names=true
jmeter.save.saveservice.default_delimiter=\t
jmeter.save.saveservice.sample_variables=case_id,region
jmeter.save.saveservice.output_format=xml
jmeter.save.saveservice.timestamp_format=ms
jmeter.save.saveservice.error_count=true
